name: CD Pipeline (Dev)

on:
  workflow_run:
    workflows: ["CI Pipeline (Fork-safe)"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/2025_SEASONTHON_TEAM_80_BE/src/main/resources

            printf '%s\n' "${{ secrets.APPLICATION_YML }}" > /home/ubuntu/2025_SEASONTHON_TEAM_80_BE/src/main/resources/application.yml
            printf '%s\n' "${{ secrets.DOCKER_COMPOSE_YML }}" > /home/ubuntu/2025_SEASONTHON_TEAM_80_BE/docker-compose.yml
            printf '%s\n' "${{ secrets.ENV }}" > /home/ubuntu/2025_SEASONTHON_TEAM_80_BE/.env

            cd /home/ubuntu/2025_SEASONTHON_TEAM_80_BE

            echo "===== Docker Hub 로그인 ====="
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

            echo "===== 이미지 최신화 및 컨테이너 실행 ====="
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
